export * from './apresentacao.repository';
export * from './instrumento-musica.repository';
export * from './instrumento.repository';
export * from './musica-aprendida.repository';
export * from './musica-apresentacao.repository';
export * from './musica.repository';
export * from './tocador-apresentacao.repository';
export * from './tocador-musica.repository';
export * from './tocador.repository';
